### ISSUE TITLE
Add support for UserId

### ISSUE THREAD

**Issue by joshbouganim** [serilog-contrib/serilog-sinks-applicationinsights#104]
in a similar vein to #64, can built-in support for UserId be added?  if the LogContext has a "UserId" property, add it to AI as User.Id.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
