### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by cmeeren** [serilog-contrib/serilog-sinks-applicationinsights#108]
I always try to read changelogs before upgrading nugets, but this project has no up-to-date changelog. I suggest keeping the changelog up-to-date, containing all changes in all released version.

**Comment by aloneguid** [comment]
It would be awesome, I'd probably need some help to automate this.

**Comment by cmeeren** [comment]
In the meantime, the library doesn't seem to update that often, so perhaps it would be possible to do it manually? :)

**Comment by aloneguid** [comment]
I personally won't have time to do it but happy for anyone to pick this up.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!

**Comment by cmeeren** [comment]
> * Feel free to comment here, letting us know it's still a problem

Yes, I would very much still like to see a changelog for new releases. 👍

**Comment by nblumhardt** [comment]
It looks like this could be automated via https://github.com/marketplace/actions/create-release - most Serilog projects now use GitHub Releases instead of a text changelog. I've switched the repo over from AppVeyor to Actions now, so hopefully not too many hurdles to jump. Anyone keen to give this a shot? Any and all help much appreciated 🙏
