### ISSUE TITLE
TelemetryConfiguration.Active returns empty key

### ISSUE THREAD

**Issue by batizar** [serilog-contrib/serilog-sinks-applicationinsights#110]
Using Serilog in WebJob 3.0, following the instructions here but `TelemetryConfiguration.Active` is not able to get the configurations that is already setup from service provider and it always returns with default config with an empty app insights key. Here is the code sample I used.

```
.ConfigureLogging((context, b) =>
{
	b.SetMinimumLevel(LogLevel.Debug);
	b.AddConsole();
	
	var appInsightsKey = context.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];
	if (!string.IsNullOrEmpty(appInsightsKey))
	{
		b.AddApplicationInsights(o => o.InstrumentationKey = appInsightsKey);
	}
	
	b.AddSerilog(Log.Logger);
})
.ConfigureServices((hostContext, services) =>
{
	services.AddOptions();
	services.Configure<AppConfig>(_configuration.GetSection("AppConfig"));
	services.AddTransient<IDoSomethingService, DoSomethingService>();
})
.UseSerilog((hostContext, loggerConfig) =>
{
	loggerConfig
		.ReadFrom.Configuration(_configuration)		
		.Enrich.FromLogContext()
		.WriteTo.Console(new CompactJsonFormatter())
		.WriteTo.ApplicationInsights(TelemetryConfiguration.Active, new CustomTelemetryConverter());
})
```
But manually getting `TelemetryConfiguration` from service provider fixes the issue.

```
var telemetryConfig = (TelemetryConfiguration)_serviceProvider.GetRequiredService(typeof(TelemetryConfiguration));
loggerConfig.WriteTo.ApplicationInsights(telemetryConfig, new CustomTelemetryConverter());
```

Thanks.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
