### ISSUE TITLE
LogWarning shows as Information on AppInsights

### ISSUE THREAD

**Issue by batizar** [serilog-contrib/serilog-sinks-applicationinsights#111]
Calling `LogWarning` from `Microsoft.Extensions.Logging.ILogger` object submits as `Information` on AppInsights. 

It works fine if I take out `Serilog` and use `Microsoft.Extensions.Logging` instead.

`_logger.LogWarning("Warning message!");`

File:
```
{
	"@t": "2019-05-09T03:25:43.1194274Z",
	"@mt": "Warning message!",
	"@l": "Warning",
	"SourceContext": "DemoService.Functions",
	"Category": "Function.ProcessMessageAsync",
	"LogLevel": "Information",
	"MS_FunctionInvocationId": "7148a128-2e1d-46de-86c7-3af9e6489147",
	"MS_FunctionName": "ProcessServiceBusMessageAsync",
	"MS_Event": "FunctionStart",
	"MS_HostInstanceId": "00000000-0000-0000-0000-000000000000",
	"ThreadId": 11,
	"MachineName": "",
	"ProcessId": 20632,
	"ProcessName": "dotnet",
	"EnvironmentUserName": "",
	"Version": "1.0.0.0",
	"Application": "DemoService"
}
```
App Insights Custom Dimensions:
```
{
	"Category": "Function.ProcessMessageAsync",
	"LogLevel": "Information",
	"Application": "DemoService",
	"MS_FunctionInvocationId": "e6e85d7e-fec7-46e1-8ab8-697a2e236550",
	"EnvironmentUserName": "",
	"MessageTemplate": "Warning message!",
	"MS_HostInstanceId": "00000000-0000-0000-0000-000000000000",
	"MachineName": "",
	"SourceContext": "DemoService.Functions",
	"MS_FunctionName": "ProcessMessageAsync",
	"ProcessName": "dotnet",
	"ProcessId": "27820",
	"ThreadId": "6",
	"MS_Event": "FunctionStart",
	"Version": "1.0.0.0"
}
```
Thanks.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
