### ISSUE TITLE
Adding Nugget package in Azure Functions 2 shows error

### ISSUE THREAD

**Issue by ajmal744** [serilog-contrib/serilog-sinks-applicationinsights#114]
On adding this package in Azure Functions 2 it says not supported target framework

**Comment by aloneguid** [comment]
Can you provide more details please.

**Comment by ajmal744** [comment]
![image](https://user-images.githubusercontent.com/516313/60184415-ed0d7100-981f-11e9-83cb-064389073a68.png)

**Comment by ajmal744** [comment]
My project file 
![image](https://user-images.githubusercontent.com/516313/60184641-53928f00-9820-11e9-8d69-c0f5abd59559.png)

**Comment by ajmal744** [comment]
Basically I have a Azure functions v2 project, and when I add Serilog.Sinks.ApplicationInsights it throws an error as you see in screenshots above.

Thank you so much for looking into this.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
