### ISSUE TITLE
Provide capability to specify which properties to use for assigning AI context

### ISSUE THREAD

**Issue by tomkerkhove** [serilog-contrib/serilog-sinks-applicationinsights#123]
As of today, the sink provides some default properties that it will forward to the Application Insights context such as `operationId`.

It would be good if we could change the default names so that it uses other ones, allowing it to align with our existing naming (standards).

## Proposal
```csharp
 var log = new LoggerConfiguration()
                .WriteTo
                .ApplicationInsights(TelemetryConfiguration.Active, TelemetryConverter.Traces, enrichmentOptions =>
                {
                    enrichmentOptions.PropertyNames.OperationId = "operation-id";
                })
                .CreateLogger();
```

Happy to contribute this if you want

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
