### ISSUE TITLE
How to use StartOperation in TelemetryClient?

### ISSUE THREAD

**Issue by Vijay-Nirmal** [serilog-contrib/serilog-sinks-applicationinsights#124]
We can inherit `TraceTelemetryConverter` or `ITelemetryConverter` to write a specifiv properties to `RequestTelemetry` or `DependencyTelemetry` but I can't find a way to do `StartOperation` in `TelemetryClient`

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
