### ISSUE TITLE
Is there a way to force the connection through a corporate proxy?

### ISSUE THREAD

**Issue by Eldorian** [serilog-contrib/serilog-sinks-applicationinsights#126]
I didn't see a way to use an httpclienthandler to add a proxy config for the connection to go through, is there a way to do this or am I blind to it?

**Comment by hosseinnassiri** [comment]
> I didn't see a way to use an httpclienthandler to add a proxy config for the connection to go through, is there a way to do this or am I blind to it?

I have the same issue, have you found any solution?

**Comment by Eldorian** [comment]
> > I didn't see a way to use an httpclienthandler to add a proxy config for the connection to go through, is there a way to do this or am I blind to it?
> 
> I have the same issue, have you found any solution?

Nope, basically had to create a global proxy setting and have all traffic go through that. Would rather be able to control it but it is what it is.

**Comment by hosseinnassiri** [comment]
> > > I didn't see a way to use an httpclienthandler to add a proxy config for the connection to go through, is there a way to do this or am I blind to it?
> > 
> > 
> > I have the same issue, have you found any solution?
> 
> Nope, basically had to create a global proxy setting and have all traffic go through that. Would rather be able to control it but it is what it is - it's on the app insights side that is the problem.

I tried defining global proxy in web.config of my asp.net core app, it didn't work for me. may I ask what did you do?

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
