### ISSUE TITLE
Log level no longer sending as custom dimension

### ISSUE THREAD

**Issue by gradyal** [serilog-contrib/serilog-sinks-applicationinsights#127]
I have a .NET Framework 4.8 project that is reading in settings from the ```app.config```. It's using the ```TraceTelemetryConverter```. I had some queries written in Application Insights that I just realized were broken because the log level is no longer coming across. 

What is the best way to send log level? The documentation seems to indicate this is possible by subclassing ```TraceTelemetryConverter```, but how do I use the subclass with the ```ReadFrom.AppSettings()``` method? I tried just replacing the ```serilog:write-to:ApplicationInsights.telemetryConverter``` value in the ```app.config``` with the subclass (including the namespace) but got the following exception on app launch:

![image](https://user-images.githubusercontent.com/5721295/73579155-4c330400-4447-11ea-9993-37f8ec72dac0.png)

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
