### ISSUE TITLE
Requests are being logged as Traces

### ISSUE THREAD

**Issue by SteveDrakey** [serilog-contrib/serilog-sinks-applicationinsights#129]
This maybe by design.

The docs say 

> Note: Whether you choose Events or Traces, if the LogEvent contains any exceptions it will always be sent as ExceptionTelemetry.

So when `UseSerilogRequestLogging` writes to the logger, it does not know if the logger is `applicationinsights` and `applicationinsights` does not know that its a request log, so it gets logged as a trace.

I would like `Log.LogInformation()` to write the the Application Insights sink but would also like any requests logged via `UseSerilogRequestLogging` to be logged via Application Insights but to be logged as the correct type.

 don't want to add the default app insights logging to achieve this.

Can this be done? thanks

**Comment by jstafford5380** [comment]
I could be wrong or misreading what you're trying to do, but I think anything sent to AI is a trace. In addition to that, anything lower than warning doesn't appear in AI at all and anything above warning appears as an Error. So effectively, in AI, all warnings are traces and all traces are warnings lol. At least, that is what I have found.

I'm wondering if all the additional logs seen in AI aren't under your control, because it's an insights product, not necessarily a logging product. If I leave all settings the same and turn on console logging in an app service or even just app log streams, all of my logs appear correctly.

**Comment by SteveDrakey** [comment]
Thanks for getting back to me, I ended up not using Serilog for request logging, I just let AI do that.

I still let my logs flow to AI as Traces which is fine, and now that I don't call `UseSerilogRequestLogging` its all good.

I did sort of get it working with calling `UseSerilogRequestLogging`  but it just did'nt feel right, I was converting the Trace to a Request and populating props to make it show correctly in AI, but if just let AI (.net code) log to AI (azure service) then its all works so no need for `UseSerilogRequestLogging` 

A good test for me was, using a single page application that has JavaScript logging

* Log Page views from the Web via JavaScript (just let the AI framework do this)
* Log call to API from the .NET Core App (just let the AI framework do this)
* Test trace log in my API ( Serilog sends this to AI )
* Throw test exception (AI logs this for me)
* Client reports error along with an Operation ID

Then I open AI UI, but the Operation ID in the search and I can see the entire flow, he page views, trace logs, debug logs, api call, error logged from server with stack trace and the error details from the client JavaScript app.

**Comment by nblumhardt** [comment]
Hi! I think `TelemetryConverter.Events` may be designed for this scenario?

---

Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!

**Comment by EdenGoforIt** [comment]
I have no idea why it's working now with `AppInsights:{Instrumentation: ""}` in the configuration. I'm using .NET 8, Serilog, and Application Insights. Without that configuration, it shows as unconfigured and only sends **traces**, even when the severity level is set to Error. Just for others suffering from this.
