### ISSUE TITLE
Exception logs go to trace or custom events

### ISSUE THREAD

**Issue by AritraChakraborty** [serilog-contrib/serilog-sinks-applicationinsights#134]
I have configured the logs 
Log.Logger = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .WriteTo.ApplicationInsights(config["AppInsightsKey"], TelemetryConverter.Traces)
            .CreateLogger();

But whenever I log Error eg 
_logger.LogError("Error");
_logger.LogError(new Exception(), "test");

All logs are going to traces. I want them to go to exceptions. Please help.

I even followed the stack overflow recomedation
https://stackoverflow.com/questions/53075630/asp-net-core-applicationinsights-logging-errors-as-trace but it did not work :(

**Comment by AritraChakraborty** [comment]
Hi Team , Just wanted to know is thier any update on this. Thanks a lot in advance.

**Comment by joao-salgado** [comment]
When launching your log, add your exception together, like

`
catch (Exception ex)
{
     Log.Error(ex, "error");
}
`

It worked for me

**Comment by jeroenheijmans** [comment]
Should it help someone, I had the same symptom. However, it got resolved automatically:

When trying out my endpoints (specifically designed to throw an exception and cause a 500 HttpStatus) I would see `customEvents` stream in _immediately_, but _no_ `exceptions` would show up in AI.

However, after waiting a few minutes, the `exceptions` in AI started to fill up after all.

I presume this was because either there's _always_ potentially such a delay, or because I'm playing on a Free Tier with this current application, which might have slower ingestion of certain events.

Not sure if this was OP's problem, but for me a bit of patience was enough.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
