### ISSUE TITLE
Unable to write traces in application insight using asp.net console application

### ISSUE THREAD

**Issue by pushkarDO** [serilog-contrib/serilog-sinks-applicationinsights#135]
I am trying to write log traces in application insights in .net console application not .net core. I am using serilog for this. But unable to do so. Below is the log code I am using. Please provide me the solution.

public static class Log
    {
        private static Serilog.Core.Logger _log;
        static Log()
        {
            
                _log = new LoggerConfiguration()
               .MinimumLevel.Verbose().WriteTo.ApplicationInsights(Instrumentaton_Key, TelemetryConverter.Traces)
               .CreateLogger();
        }

        public static void Info(string messageTemplate)
        {
            _log.Information(messageTemplate);
        }

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
