### ISSUE TITLE
Cannot access a disposed object, Object name: 'ApplicationInsightsSink'

### ISSUE THREAD

**Issue by slanto** [serilog-contrib/serilog-sinks-applicationinsights#136]
Hi,
I am struggling with writing logs to App Insights from ASP.NET MVC application.
I get the following exception:

```
Caught exception while emitting to sink Serilog.Sinks.ApplicationInsights.ApplicationInsightsSink: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ApplicationInsightsSink'.
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSink.CheckForAndThrowIfDisposed()
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

This is my logger configuration where I write LogEvent to Traces in Application Insights. 

```
   Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Is(minimumLevel)
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithProcessId()
                .Enrich.WithProcessName()
                .Enrich.WithProperty(LoggerFields.ApplicationName, appName)                
                .WriteTo.ApplicationInsights(TelemetryConfiguration.Active, TelemetryConverter.Traces)                
                .CreateLogger();
```

Because of the mentioned error, there are no any logs with Trace type in my Application Insights. Do you have any suggestions?

The following lib's version is used:
- `Serilog.Sinks.ApplicationInsights 3.1.0`
- `Serilog 2.9.0`

**Comment by angularsen** [comment]
I'm seeing the same with the same versions of nugets, on both netcoreapp2.2 and netcoreapp3.1.

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!

**Comment by Steve887** [comment]
I am getting this error trying to log to app insights using version 4.0.0. Was there ever a resolution to this?
