### ISSUE TITLE
Allow not escaping string (the :l flag on {Message}) (or allow setting the output template)

### ISSUE THREAD

**Issue by cmeeren** [serilog-contrib/serilog-sinks-applicationinsights#137]
(Related to #117, but this issue has another focus.)

As you are probably aware, Serilog allows [setting custom output templates](https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text). The `{Message}` token supports a flag `:l` that turns off quoting of strings.

I am able to configure the output template for all my sinks except Serilog.Sinks.ApplicationInsights. It seems that Serilog.Sinks.ApplicationInsights does not use the `:l` flag, because when my message template contains a JSON string, it is escaped.

My message template is this:

```
Log.Debug("Operation {OpName}\n{InteractionData}", opName, json)
```

My wish is to have a rendered message that looks like this:

```
Operation User.byId
{
  "Input": {
    "UserId": 10036
  },
  "Output": null
}
```

Here is how the message looks in AI:

![image](https://user-images.githubusercontent.com/7766733/82663966-05089300-9c31-11ea-87a0-0d852558ca18.png)

If I view just the telemetry property corresponding to the JSON in AI, it looks even worse:

![image](https://user-images.githubusercontent.com/7766733/82664614-5f562380-9c32-11ea-8011-6d5bec709985.png)

This looks similar to how the console sink looks when just using `{Message}` (no `:l` flag):

![image](https://user-images.githubusercontent.com/7766733/82664105-44cf7a80-9c31-11ea-83ca-fe001826afc6.png)

Whereas if I specify `{Message:l}` in the output template for the console sink, it looks just like I want it to:

![image](https://user-images.githubusercontent.com/7766733/82664148-603a8580-9c31-11ea-8114-03c15c494060.png)

My guess is that if Serilog.Sinks.ApplicationInsights were to allow setting a custom output template, and I then use `{Message:l}`, then the message and/or the property in AI would look properly formatted, as shown in the last console image above.

**Comment by arslanaybars** [comment]
@cmeeren I faced with the same issue. Did you find any solution to the case?

**Comment by cmeeren** [comment]
Nope, no solution.

**Comment by arslanaybars** [comment]
I solved my issue with using custom TraceTelemetry and would like to share it here, which may help someone in the future! 🎉

Checked the broken property key and if it has. I can replace the unwished chars with string.Empty

Code talks;
```
public class AybTelemetryConverter : TraceTelemetryConverter
{
    public override IEnumerable<ITelemetry> Convert(LogEvent logEvent, IFormatProvider formatProvider)
    {
        foreach (var telemetry in base.Convert(logEvent, formatProvider))
        {
            ISupportProperties propTelematry = (ISupportProperties)telemetry;

            if (propTelematry.Properties.Any(x => x.Key == "response_body"))
            {
                var value = Regex.Replace(propTelematry.Properties["response_body"], @"\t|\n|\r", "").Replace("\\","");
                if (value.Length < 8192)
                {
                    propTelematry.Properties.Add("ResponseBody", value);
                }
                propTelematry.Properties.Remove("response_body");
            }                        
            yield return telemetry;
        }
    }
}
```

Hope it will help someone. Viso! 👋

**Comment by cmeeren** [comment]
Won't that replace even backslashes that are meant to be in the string? E.g. if the string contains a Windows path.

**Comment by arslanaybars** [comment]
Yes, you are right my solution just an easy workaround for saving the day. Otherwise need to implement :l feature

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!

**Comment by cmeeren** [comment]
This is still something I (and, I assume, @arslanaybars) would like to see implemented. The fact that it hasn't been implemented/fixed yet doesn't make it irrelevant. 🙂 I mean, if I had reported this a week ago instead of two years ago, it would have been left open, I assume?

WIth this in mind, could it be re-opened?

**Comment by nblumhardt** [comment]
Hi Christer! Thanks for the nudge.

I agree that this would be a big improvement (the old quoted style of templates are a bit hard on the eyes :-)).

I closed just about all of the open issues because we've had very little maintainer time available for the past couple of years, and with 50+ open issues it was very hard to see which are even still relevant.

I'm just filling in, for now. I can definitely review PRs - is this one you're keen on having a shot at? I think there's room in 4.0 for some breaking changes or additional configuration options, I'd be happy to help figure out an approach.

**Comment by cmeeren** [comment]
If you can guide me to what parts of the code needs changing and if it's fairly simple, then maybe, though I am currently on a strict time budget and don't really have the capacity to really delve into new codebases.

**Comment by nblumhardt** [comment]
@cmeeren thanks! I'm 99% sure that the line to change is this one:

https://github.com/serilog-contrib/serilog-sinks-applicationinsights/blob/dev/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/TelemetryConverters/TelemetryConverterBase.cs#L111

Instead of calling `RenderMessage()` it's necessary to call `Format()` on a `new MessageTemplateTextFormatter("{Message:lj}")`. The formatter would need to be reused for each event.

Apart from that change, a test to show the behavior would be needed (I think there's already test infrastructure there to get this down to a few lines of code). Let me know if you need more info 👍
