### ISSUE TITLE
Keywords in messageTemplate are not transferred to Application Insights

### ISSUE THREAD

**Issue by brunis** [serilog-contrib/serilog-sinks-applicationinsights#139]
So i'm seeing these in Seq as expected..
![Screenshot_2020-07-13 Seq](https://user-images.githubusercontent.com/2270134/87286995-3c454300-c502-11ea-8cd3-b251e111aa06.png)
But why arent they getting into ApplicationInsights? What do i need to do to get those in and be able to search by them?

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
