### ISSUE TITLE
2.10.0.0 & 2.9.0.0 Serilog doesnt log exception without exception.toString() with App Insights listener - Serilog.Sinks.ApplicationInsights

### ISSUE THREAD

**Issue by RiddhiKarani** [serilog-contrib/serilog-sinks-applicationinsights#150]
void Error(Exception exception, string messageTemplate) from Serilog.ILogger is not logging exception logs 
this one works fine - void Error(string messageTemplate)

void Error(Exception exception, string messageTemplate) from Serilog.ILogger is not logging exception logs with AppInsights listner same method logs exception without any issues with Flatfile

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
