### ISSUE TITLE
No exception raised if ApplicationInsights isn't accessible (for example wrong instrumentation key is used)

### ISSUE THREAD

**Issue by borlek** [serilog-contrib/serilog-sinks-applicationinsights#166]

**Comment by borlek** [comment]
can anybody please respond?

**Comment by nblumhardt** [comment]
Hi! This is by design, Serilog logging does not generally throw exceptions when logging fails. You can change this behavior using `AuditTo` instead of `WriteTo`, but a PR adding audit sink support would be required for this.

We don't currently have bandwidth to move this forward, but if anyone is interested in having a shot at it please let us know.
