### ISSUE TITLE
EventTelemtry instances should be created using the logEvents <RenderedMessage> instead of the <MessageTemplate>

### ISSUE THREAD

**Issue by janharders** [serilog-contrib/serilog-sinks-applicationinsights#26]
Events are created using the log event's message template an the telemetry event's name. I would suggest that the rendered message is used instead, since this is the information you want to see in Azure Portal AI / AI Analytics without having to examine the <customDimensions> property.

Code: 
``` 
public static EventTelemetry ToDefaultEventTelemetry( 
147             this LogEvent logEvent, 
148             IFormatProvider formatProvider, 
149             bool includeLogLevelAsProperty = true, 
150             bool includeRenderedMessageAsProperty = true, 
151             bool includeMessageTemplateAsProperty = true) 
152         { 
153             if (logEvent == null) throw new ArgumentNullException("logEvent"); 
154 
 
155             var telemetry = new EventTelemetry(logEvent.MessageTemplate.Text)
156             { 
157                 Timestamp = logEvent.Timestamp 
158             }; 
159 
 
160             // write logEvent's .Properties to the AI one 
161             logEvent.ForwardPropertiesToTelemetryProperties(telemetry, formatProvider, includeLogLevelAsProperty, includeRenderedMessageAsProperty, includeMessageTemplateAsProperty); 
162 
 
163             return telemetry; 
164         } 
```

**Comment by jbattermann** [comment]
Hello there! There have been some discussions and different opinions in the past (see #3 and #11) regarding what to use and apparently there's not one silver bullet as everyone would want something different to be used (and for a good reason.. everyone tracks and uses telemetry differently).

So the only suitable step forward would be to make this configurable / customizable, but that would require a bit of thinking and effort to make & keep it future-proof.

Just changing it back from MessageTemplate to RenderedMessage would break everyone else's current usage / telemetries, so I can't do that, too.


However, I am currently busy with client work & therefore can't tackle this right now.. but I'll keep it around for v3 because it does make sense to make / keep this customizable.

**Comment by aloneguid** [comment]
You might not want to see renderedMessage in events, as it includes the actual rendered message which has infinite variations. MessageTempalte is the best as it minimises the number of filters you can do in the portal.

**Comment by nblumhardt** [comment]
Closing as stale, but still interested in options for improving this if anyone can investigate/make a proposal.
