### ISSUE TITLE
Configuring sink via XML configuration?

### ISSUE THREAD

**Issue by v-glushkov** [serilog-contrib/serilog-sinks-applicationinsights#39]
Hi,

Unfortunately there's no info on XML configuration for AppInsights sink in the readme file.

I found out that for basic usage of this sink it's enough to add following lines:

<add key="serilog:using:ApplicationInsights" value="Serilog.Sinks.ApplicationInsights" />
<add key="serilog:write-to:ApplicationInsights.instrumentationKey" value="my_key" />

But is it possible to configure something else via XML? For instance I'd like to set up cloud_RoleName parameter somehow to filter events coming from different components. Is it possible?

Thanks!

**Comment by tudorsibiu90** [comment]
No response AT ALL? :(

**Comment by nblumhardt** [comment]
Hi! 👋 Thanks for getting in touch, and sorry we were unable to respond to your request. We're in the process of bringing new maintainers onto this project, and need to close stale tickets so that we can identify which items are still important to users of the sink.

If this issue still affects you:

 * Please consider whether it's a question that can be asked on Stack Overflow; if so, the `serilog` tag will get your question in front of many more people who can help you
 * Please consider whether you can research or investigate the issue and propose a solution for other users to benefit from
 * Feel free to comment here, letting us know it's still a problem

Thanks again!
